#!/usr/bin/python

"""
Los datos son recogidos con el siguiente crontab
2,12,22,32,42,52 * * * * /usr/local/bin/rtl_433 -q -G -T 60 -F json 2>/dev/null >>/var/log/rtl_433.log
"""

import sys

FICHERO = "/var/log/rtl_433.log"
nan = NaN = NAN = None

if len( sys.argv ) < 2:
    medidas = {}
    for linea in file( FICHERO ):
        try:
            objeto = eval( linea.strip() )
        except:
            objeto = {}
        if "channel" in objeto and "humidity" in objeto and "id" in objeto and objeto[ "id" ] in [ 10, 195, 156, 59, 48 ]:
            medidas[ objeto[ "channel" ] ] = objeto[ "humidity" ]
    if 1 in medidas:
        print "sensor1.value", medidas[ 1 ]
    if 2 in medidas:
        print "sensor2.value", medidas[ 2 ]
    if 3 in medidas:
        print "sensor3.value", medidas[ 3 ]
elif sys.argv[ 1 ] == "autoconf":
    print "yes"
elif sys.argv[ 1 ] == "config":
    print """graph_title Humedad
graph_args --upper-limit 100 -l 0
graph_vlabel %
graph_scale no
graph_category sensores
sensor1.label Habitacion Pablo
sensor2.label Habitacion Montse y Aurelio
sensor3.label Exterior
"""
